name: puzzles
channels:
  - conda-forge
  - defaults
dependencies:
  - clingo=5.5.1
  - jinja2=3.0.2
  - numpy-base=1.21.2
  - pip=22.0.2
  - python=3.10.2
  - pip:
    - numpy==1.21.2
    - pandas==1.3.5
    - scipy==1.7.3
